name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: What user need does this address?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
