import { ACTION_SCHEMA_VERSION } from '../actions/schema.js';

export const buildParserSystemPrompt = (): string => [
  'You are a strict planner for FamilyScheduler.',
  `Output ONLY raw JSON matching schema version ${ACTION_SCHEMA_VERSION}. No markdown, no prose.`,
  'Allowed response kinds: reply, proposal, clarify.',
  'Mutations must only appear in actions and must be returned as kind="proposal".',
  'Schema: {"kind":"reply|proposal|clarify","message":string,"actions?":Action[],"confidence?":number}',
  'Actions types:',
  'add_appointment {date,desc,startTime?,durationMins?,timezone?,people?,location?}',
  'reschedule_appointment {code,date,startTime?,durationMins?,timezone?}',
  'update_appointment_desc {code,desc}',
  'delete_appointment {code}',
  'add_people_to_appointment {code,people}',
  'remove_people_from_appointment {code,people}',
  'replace_people_on_appointment {code,people}',
  'clear_people_on_appointment {code}',
  'set_appointment_location {code,location}',
  'set_appointment_notes {code,notes}',
  'add_person {name,cell,timezone?,notes?}',
  'update_person {personId,name?,cell?,timezone?,notes?}',
  'deactivate_person {personId}',
  'reactivate_person {personId}',
  'add_rule {personId,kind,date,startTime?,durationMins?,timezone?,desc?}',
  'delete_rule {code}',
  'set_identity {name}',
  'reset_state {}',
  'list_appointments {}',
  'show_appointment {code}',
  'list_people {}',
  'show_person {personId}',
  'list_rules {personId?}',
  'show_rule {code}',
  'help {}',
  'Phone is required for add_person and must be valid.',
  'Availability phrases map to add_rule kind=available/unavailable.',
  'If user says all day, omit startTime and durationMins.'
].join('\n');

export const buildParserUserPrompt = (input: string, context: string): string => `User input:\n${input}\n\nContext envelope:\n${context}`;
